<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy</name>
   <tag></tag>
   <elementGuidId>115ba99b-3881-412b-8363-4b0f38fcb880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-danger.btn-block.btn-lg.buy-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/div[2]/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16243e78-896f-4407-81a8-c0221c9fd2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/buy?subscription_id=16</value>
      <webElementGuid>acfb1fbb-f840-4f39-98a2-8ddd2548456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-danger btn-block btn-lg buy-button</value>
      <webElementGuid>324fe4da-643f-46d0-b86d-00460a006bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy </value>
      <webElementGuid>d3ce1c39-167d-4da6-863a-8f4b71196968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-page-wrapper main-content&quot;]/div[@class=&quot;container-fluid home-container home&quot;]/div[@class=&quot;main-packages-wrapper main-container mb-5&quot;]/div[@class=&quot;pricing-box d-flex w-100&quot;]/div[@class=&quot;pricing-action&quot;]/a[@class=&quot;btn btn-outline-danger btn-block btn-lg buy-button&quot;]</value>
      <webElementGuid>055179a8-9132-4d73-aa7f-27f6edc5a9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div[2]/div/div[4]/a</value>
      <webElementGuid>75f00edc-3cb8-4a2d-8d8b-b6087297b312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy')]</value>
      <webElementGuid>ce51d74a-14d1-4f39-a7b9-21291747472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::a[1]</value>
      <webElementGuid>08762eb6-46e6-4042-b8bf-0b3231bff8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::a[1]</value>
      <webElementGuid>c8cc6f5f-307c-4f7c-b70d-0c4dd9d57293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/preceding::a[1]</value>
      <webElementGuid>3053002a-e71d-4279-bbd9-d0eed2791ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[2]/preceding::a[1]</value>
      <webElementGuid>cd15d4c4-fdb7-421e-9e71-622f99d995a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy']/parent::*</value>
      <webElementGuid>78158b2f-5649-49e3-ad3f-008dbffb89ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/buy?subscription_id=16')]</value>
      <webElementGuid>1ec4b086-529e-4535-864e-ff2a90edbd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>0f1769b1-376a-4cf5-b281-75cf568c01c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/buy?subscription_id=16' and (text() = 'Buy ' or . = 'Buy ')]</value>
      <webElementGuid>3c475609-e9c2-4f34-8667-c9e58b08ee76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
