<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Upcoming</name>
   <tag></tag>
   <elementGuidId>4293f50a-3bc5-4783-bc25-d30a1add5e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarText']/ul/li/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>853666ec-34c9-48be-b686-a7373bfd8e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/upcoming</value>
      <webElementGuid>01dbb20d-c7bf-44b5-b941-f6dd3134f8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>d0b96f77-a31f-41f2-b69c-b5703e0ba7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Upcoming </value>
      <webElementGuid>f2170b7d-e994-4f67-9f85-4cbb13fd28e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarText&quot;)/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item hover-wrapper&quot;]/div[@class=&quot;dropdown-menu-hover-wrapper&quot;]/div[@class=&quot;dropdown-menu submenu-wrapp&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>18a03dc3-231e-42e8-a902-dcb4ccd2337f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarText']/ul/li/div/div/a</value>
      <webElementGuid>a5c9c703-eabf-44c6-a35f-3a1b02c19a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Upcoming')]</value>
      <webElementGuid>52cefed5-52fc-4018-b287-0ee3a5e34cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-Demand'])[1]/preceding::a[1]</value>
      <webElementGuid>d9d4f08c-0939-4f58-9431-a80ba5ade773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passes'])[1]/preceding::a[2]</value>
      <webElementGuid>dcfdbe5d-bd1c-4368-b3cb-b36b6e8c39ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upcoming']/parent::*</value>
      <webElementGuid>fd724b2c-fc17-44fa-a1d2-7d0c90d95ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/upcoming')]</value>
      <webElementGuid>19090442-a1b7-4974-9bd3-38fc7b840245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>1f962593-1bd4-49fe-8e3e-af8b68d35036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/upcoming' and (text() = ' Upcoming ' or . = ' Upcoming ')]</value>
      <webElementGuid>12fb8ef1-d8de-458d-9c81-307f93c34ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
