<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceitar</name>
   <tag></tag>
   <elementGuidId>4acc317b-8791-4966-a22b-c9948a5ac15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-auto.cursor-pointer.bg-header.text-white.py-1.px-2.rounded.shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/header/div/div[3]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8294f8e1-4a6d-4b69-a62c-c3a5a02fb4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto cursor-pointer bg-header text-white py-1 px-2 rounded shadow</value>
      <webElementGuid>be6c3384-e275-496e-b9af-a53f78faa207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Aceitar
      </value>
      <webElementGuid>e0ae18ce-3bb9-442d-8ae9-b3376ea1160a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/div[@class=&quot;fixed top-0 left-0 right-0 z-40&quot;]/div[1]/header[@class=&quot;relative bg-gradient-tim&quot;]/div[1]/div[@class=&quot;fixed mobile:bottom-12 bottom-0 left-0 right-0 text-center&quot;]/div[@class=&quot;p-2 mb-6 mx-4 bg-zinc-600 bg-opacity-90 rounded shadow&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;m-auto cursor-pointer bg-header text-white py-1 px-2 rounded shadow&quot;]</value>
      <webElementGuid>f75d4225-4819-4d8e-aa1e-f31ccae9985c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/header/div/div[3]/div/div[2]/div</value>
      <webElementGuid>ed71d9a9-9e34-416e-9d87-d2d493d8154a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. Ao continuar navegando, você concorda com estas condições.'])[1]/following::div[2]</value>
      <webElementGuid>29ce8908-c1c6-46f4-a50b-43fa4b86c1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacidade'])[1]/following::div[2]</value>
      <webElementGuid>82646129-20d3-4714-af71-9720a1dc0cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acesse Sportito'])[1]/preceding::div[18]</value>
      <webElementGuid>22ea52fa-bd70-46bb-8e39-1d9b6108195b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fazer login'])[1]/preceding::div[21]</value>
      <webElementGuid>822ecc40-d24f-4b3b-a59e-74e8882beefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceitar']/parent::*</value>
      <webElementGuid>cbc90425-e072-48e6-9ed3-01d8421df9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/div</value>
      <webElementGuid>934f305f-e37c-47db-8942-1a8b07a5f559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
        Aceitar
      ' or . = '
        Aceitar
      ')]</value>
      <webElementGuid>eeef9c62-728d-4d9c-8d82-df94d8f78b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
