<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceitar (1)</name>
   <tag></tag>
   <elementGuidId>6ebbf55b-0afb-409d-b139-d45b2d60d3c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-auto.cursor-pointer.bg-header.text-white.py-1.px-2.rounded.shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/header/div/div[3]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>758338d7-8b63-43f8-b45d-00af3b32b797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto cursor-pointer bg-header text-white py-1 px-2 rounded shadow</value>
      <webElementGuid>8b80a3a7-fb19-420b-856c-3ef7a10a71f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Aceitar
      </value>
      <webElementGuid>0a1c64f0-e8c8-4760-b15f-929d12713240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/div[@class=&quot;fixed top-0 left-0 right-0 z-40&quot;]/div[1]/header[@class=&quot;relative bg-gradient-tim&quot;]/div[1]/div[@class=&quot;fixed mobile:bottom-12 bottom-0 left-0 right-0 text-center&quot;]/div[@class=&quot;p-2 mb-6 mx-4 bg-zinc-600 bg-opacity-90 rounded shadow&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;m-auto cursor-pointer bg-header text-white py-1 px-2 rounded shadow&quot;]</value>
      <webElementGuid>78a4e9c3-274b-4e1c-98d9-1caf51942fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/header/div/div[3]/div/div[2]/div</value>
      <webElementGuid>eeb76e80-84c6-49f6-bc71-2f545dfe3bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. Ao continuar navegando, você concorda com estas condições.'])[1]/following::div[2]</value>
      <webElementGuid>c435f720-3624-4e41-a882-0f4f94374846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacidade'])[1]/following::div[2]</value>
      <webElementGuid>855464db-995f-404e-8bd8-3f2cb218881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acesse Sportito'])[1]/preceding::div[18]</value>
      <webElementGuid>1785fd04-9e24-4b95-a247-aadd25cdbb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fazer login'])[1]/preceding::div[21]</value>
      <webElementGuid>91744112-c91e-4761-9aba-d9dbcfc2b5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceitar']/parent::*</value>
      <webElementGuid>0f6c700c-bee9-41d0-9247-c8eda1cbd747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/div</value>
      <webElementGuid>164c0529-6319-4995-8728-6a225c7a86f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
        Aceitar
      ' or . = '
        Aceitar
      ')]</value>
      <webElementGuid>97265513-4414-4ba6-87ee-e80cb37fecd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
