<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Notcias_h-full m-auto rounded imageBanner</name>
   <tag></tag>
   <elementGuidId>86cfba59-d7fb-49df-a82f-0ac01e36b1c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div[3]/div/section/div/div[3]/div/a/article/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94d80425-05d7-442b-af1f-f37a967682ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15534224/original/open-uri20230503-18-1fhjq4a?1683141114</value>
      <webElementGuid>940162b5-e6ab-423f-b8ed-bf1f50bc902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15534224/original/open-uri20230503-18-1fhjq4a?1683141114</value>
      <webElementGuid>0306acdb-7297-4bea-96dd-828e70cda5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>640px</value>
      <webElementGuid>08008724-5a26-4d5b-a68f-995f53281833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>0057c377-ac30-4f01-b2fe-9c1682b35cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c65199b9-ed5c-49bc-a053-c0aded013737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full m-auto rounded imageBanner</value>
      <webElementGuid>eb60853a-229f-473d-b8ff-ef8de424868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/main[@class=&quot;container flex-grow min-h-screen-custom mx-auto  desktop:mt-[5.9rem] mobile:mt-14&quot;]/div[@class=&quot;container relative mx-auto&quot;]/div[@class=&quot;gap-4 desktop:grid desktop:grid-cols-12&quot;]/div[@class=&quot;flex flex-col col-span-3 col-start-10&quot;]/section[1]/div[1]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;desktop:border-b desktop:border-gray-300&quot;]/a[1]/article[@class=&quot;mobile:px-4 mobile:w-full&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;h-[231px] mobile:h-[256px] rounded-lg overflow-hidden relative flex&quot;]/img[@class=&quot;h-full m-auto rounded imageBanner&quot;]</value>
      <webElementGuid>fd4a9d92-e6ab-4729-9b1e-1b47cc2277ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div[3]/div/section/div/div[3]/div/a/article/div/div/img</value>
      <webElementGuid>f79a3bcf-5b43-454f-992b-2a087985d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://timnews.com.br/system/images/photos/15534224/original/open-uri20230503-18-1fhjq4a?1683141114']</value>
      <webElementGuid>aa915c8d-5150-415c-9d30-3d921cafe4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/img</value>
      <webElementGuid>c7aacf36-f490-44d9-8a90-0b9dbb0d1190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/images/photos/15534224/original/open-uri20230503-18-1fhjq4a?1683141114' and @alt = 'https://timnews.com.br/system/images/photos/15534224/original/open-uri20230503-18-1fhjq4a?1683141114']</value>
      <webElementGuid>2d749d72-5e96-4347-8fcc-365aac7adbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
