<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ENTRETENIMENTO</name>
   <tag></tag>
   <elementGuidId>9ca8cdd7-b532-49d8-9946-7421658921ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b304ca1f-564c-4c3f-8245-eab61721242b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/favorites/Entretenimento%2617%26entities%26false%26true/771:2705:ProfileNode:Entretenimento:entities:17/feed</value>
      <webElementGuid>4fdce5ac-b521-4b58-bb68-5672d664aeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>03a5d71d-51ed-46fd-9ca0-e3a4a1c64eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ENTRETENIMENTO
      </value>
      <webElementGuid>b8addef0-99e9-4769-9746-a099750b2a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/div[@class=&quot;fixed top-0 left-0 right-0 z-40&quot;]/div[1]/div[@class=&quot;bg-white border-t border-b-2 mobile:hidden border-slate-100&quot;]/div[@class=&quot;container flex content-between justify-between px-10 mx-auto h-9 mobile:hidden&quot;]/div[@class=&quot;h-full flex text-[11px] font-medium  no-underline text-[#00152E] hover:text-lighthighlight mobile:hidden&quot;]/a[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>d204d3e3-3d72-4a1b-84bb-41d49e7ea810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/div[3]/a</value>
      <webElementGuid>a660d78f-0643-4aea-8fe9-caa4b6f3ba2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ENTRETENIMENTO')]</value>
      <webElementGuid>eb2fba79-966f-41b3-8eb9-223b82c1c058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPORTES'])[1]/following::a[1]</value>
      <webElementGuid>3d8895d9-c1ed-456f-8f15-fcb66cee976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTÍCIAS'])[1]/following::a[2]</value>
      <webElementGuid>8952e14d-43c2-4683-816d-094f6251bbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESTILO DE VIDA'])[1]/preceding::a[1]</value>
      <webElementGuid>4027f1fa-4f2b-4390-bbbc-49567271aec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TECNOLOGIA'])[1]/preceding::a[2]</value>
      <webElementGuid>5de31159-f19f-48b7-9907-365c31005a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENTRETENIMENTO']/parent::*</value>
      <webElementGuid>331a636d-f8b5-4b84-877b-482f2298f010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/favorites/Entretenimento%2617%26entities%26false%26true/771:2705:ProfileNode:Entretenimento:entities:17/feed')]</value>
      <webElementGuid>35bc5d7d-01c8-4dad-a009-61d582e909d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/a</value>
      <webElementGuid>b144af5f-ce64-496e-96bc-0c219a4e4c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/favorites/Entretenimento%2617%26entities%26false%26true/771:2705:ProfileNode:Entretenimento:entities:17/feed' and (text() = '
        ENTRETENIMENTO
      ' or . = '
        ENTRETENIMENTO
      ')]</value>
      <webElementGuid>063ed2d6-a24f-47a2-8e1d-7cacb69037a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
