<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ESPORTES</name>
   <tag></tag>
   <elementGuidId>57ca9746-5281-4b85-9c8e-ca1a008095ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>462999b0-1c4e-499b-afde-9e0f3b3eacae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/favorites/Esportes%2644%26entities%26false%26true/771:2599:ProfileNode:Esportes:entities:44/feed</value>
      <webElementGuid>8e8ef3ed-8cb4-4d1d-ba44-2f34b90232d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>e1fbe382-fc97-4f2c-b7ad-28ad13f5c130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ESPORTES
      </value>
      <webElementGuid>df475a8c-51c9-43d3-818c-33e97a0bebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/div[@class=&quot;fixed top-0 left-0 right-0 z-40&quot;]/div[1]/div[@class=&quot;bg-white border-t border-b-2 mobile:hidden border-slate-100&quot;]/div[@class=&quot;container flex content-between justify-between px-10 mx-auto h-9 mobile:hidden&quot;]/div[@class=&quot;h-full flex text-[11px] font-medium  no-underline text-[#00152E] hover:text-lighthighlight mobile:hidden&quot;]/a[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>ab4412c4-8eee-4567-b8c5-538434811361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>39bf2f63-8af7-477a-be64-d251af76d3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ESPORTES')]</value>
      <webElementGuid>61383710-b5e1-4072-b338-7e0f02a229d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTÍCIAS'])[1]/following::a[1]</value>
      <webElementGuid>453d9ea9-03a5-43db-b3bc-f1a950c84955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fazer login'])[1]/following::a[2]</value>
      <webElementGuid>5887b0d1-91ae-4627-aa89-14e66e59dc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTRETENIMENTO'])[1]/preceding::a[1]</value>
      <webElementGuid>b0669160-66d6-4fb0-9f1f-b8089ee42f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESTILO DE VIDA'])[1]/preceding::a[2]</value>
      <webElementGuid>5108e6cb-64a3-4b84-8a41-db353508acae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESPORTES']/parent::*</value>
      <webElementGuid>49f5bd88-eacf-405b-8962-1b2857c0aa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/favorites/Esportes%2644%26entities%26false%26true/771:2599:ProfileNode:Esportes:entities:44/feed')]</value>
      <webElementGuid>6ae8bb1a-450d-4935-bda3-caf3fabe8cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1a6de9f0-54c9-4405-8670-6a03db037c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/favorites/Esportes%2644%26entities%26false%26true/771:2599:ProfileNode:Esportes:entities:44/feed' and (text() = '
        ESPORTES
      ' or . = '
        ESPORTES
      ')]</value>
      <webElementGuid>4c1100ed-8fba-432c-a6f5-1c1f91bfe3c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
