<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7206d50b-e164-4710-b9ac-b790d58ba1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;TIM News&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SiteHeader']/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df2dbdb2-8fd9-467b-a474-3ce5106554df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/site_template_brands/large_logos/15/original/timnews.svg?1637269988</value>
      <webElementGuid>97931614-4f27-4eeb-be8a-9c4935a56632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>109</value>
      <webElementGuid>2d677f03-9d86-45e6-82a0-8297c13b83c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>fe6aff65-e233-4d34-b562-920a6466aaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TIM News</value>
      <webElementGuid>1c98eed5-a40f-44b9-b077-69c4dabca59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteHeader&quot;)/div[@class=&quot;grid w-full grid-cols-3 gap-0 desktop:hidden&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;desktop:pl-[9px] flex h-14 mobile:m-auto mobile:scale-95&quot;]/a[@class=&quot;nuxt-link-active m-auto no-underline&quot;]/img[1]</value>
      <webElementGuid>fdf58887-2e1d-4646-992c-b0290860167b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SiteHeader']/div/div[2]/div/a/img</value>
      <webElementGuid>a2ad36bb-084a-4a5c-8f52-dcef3754bbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TIM News']</value>
      <webElementGuid>2533ad34-8bbc-46e4-8ab5-d905e05dd0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7a4763a9-6fcc-45b2-9073-205a8b254049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/site_template_brands/large_logos/15/original/timnews.svg?1637269988' and @alt = 'TIM News']</value>
      <webElementGuid>4debf886-3229-49bf-8973-870d78a5b2df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
