<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7206d50b-e164-4710-b9ac-b790d58ba1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;TIM News&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SiteHeader']/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33556993-cdfd-48f8-abfd-fad9f659c2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/site_template_brands/large_logos/15/original/timnews.svg?1637269988</value>
      <webElementGuid>6329cb88-8a9d-4239-96db-53bff9e0ac1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>109</value>
      <webElementGuid>f0573eef-4367-4f85-a930-e7b0e998dcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>8860619c-4c1a-4bae-99fc-c540bc7a0abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>TIM News</value>
      <webElementGuid>b2a5c7d0-925f-4fc9-81fb-15d99311b4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteHeader&quot;)/div[@class=&quot;grid w-full grid-cols-3 gap-0 desktop:hidden&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;desktop:pl-[9px] flex h-14 mobile:m-auto mobile:scale-95&quot;]/a[@class=&quot;nuxt-link-active m-auto no-underline&quot;]/img[1]</value>
      <webElementGuid>375850f6-0aa7-45cf-8826-507cea2ae62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SiteHeader']/div/div[2]/div/a/img</value>
      <webElementGuid>1be409d4-0fc6-4b40-8c0e-2e6616f96119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='TIM News']</value>
      <webElementGuid>0db3e483-268b-4664-915d-e043bbce734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d1a79e53-bd79-411b-85fa-b1b44e96ab54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/site_template_brands/large_logos/15/original/timnews.svg?1637269988' and @alt = 'TIM News']</value>
      <webElementGuid>9e040d0a-c900-4a4d-b0ef-ac4b0d495a2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
