<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__w-full h-auto m-auto rounded mobileima_73a792</name>
   <tag></tag>
   <elementGuidId>19e0e963-c4f3-4c48-a5be-1ead98a37b6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='searchQueryEventFeed']/section[2]/div/div/div[3]/article/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63f645a4-f758-4899-b15c-4a91e4be736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15548848/original/data?1683829826</value>
      <webElementGuid>01261053-375c-4caf-975d-9493703e604d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>54b8c789-5ee1-4db3-ba8e-6e60ad71293d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>ace37dac-b672-4572-9c08-bccddb11d9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15548848/original/data?1683829826</value>
      <webElementGuid>09b6c043-fbdc-455f-a05d-8341070ce2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>547621b8-1405-40d8-8217-2dca2210c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto m-auto rounded mobile:imageBanner</value>
      <webElementGuid>606c6aa1-5279-44cf-a8f6-3982c312aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchQueryEventFeed&quot;)/section[@class=&quot;desktop:grid desktop:gap-2 desktop:grid-cols-10&quot;]/div[@class=&quot;mb-5 desktop:col-span-7&quot;]/div[@class=&quot;relative px-2 mb-5&quot;]/div[@class=&quot;my-2&quot;]/article[@class=&quot;p-1 mx-auto my-1 rounded bg-backgroundoverlay mobile:shadow&quot;]/a[1]/div[@class=&quot;desktop:grid desktop:gap-1 desktop:grid-cols-12 mb-2&quot;]/div[@class=&quot;relative flex col-span-3 mobile:col-span-4&quot;]/img[@class=&quot;w-full h-auto m-auto rounded mobile:imageBanner&quot;]</value>
      <webElementGuid>9a754999-bb99-4fdb-b2e6-c08fdcc2201d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='searchQueryEventFeed']/section[2]/div/div/div[3]/article/a/div/div/img</value>
      <webElementGuid>f669a427-6457-4826-aeac-c9b41f230f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://timnews.com.br/system/images/photos/15548848/original/data?1683829826']</value>
      <webElementGuid>244bbaf5-6c35-45c6-b4b7-bcca2df983bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/article/a/div/div/img</value>
      <webElementGuid>fc13c2cb-c30d-49bf-ab73-fda171ef8773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/images/photos/15548848/original/data?1683829826' and @alt = 'https://timnews.com.br/system/images/photos/15548848/original/data?1683829826']</value>
      <webElementGuid>d462cafe-236e-4cbf-b082-2aed10e351cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
