<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__h-full m-auto rounded imageBanner</name>
   <tag></tag>
   <elementGuidId>e9441e28-c55d-4665-b590-a84d8be90af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FavoritesFeed']/section/div[4]/div[2]/div[2]/article/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>831a7910-b35d-43b0-9acf-26613935f9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15562810/original/open-uri20230519-18-2qfmd6?1684508195</value>
      <webElementGuid>5587c6b2-c71c-4609-be3a-97a270e8ef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15562810/original/open-uri20230519-18-2qfmd6?1684508195</value>
      <webElementGuid>3edb8a13-d823-498b-abab-3299080f2b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>640px</value>
      <webElementGuid>ff4e9b35-96ef-43ae-bfa4-99dc454cab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>5b49a803-1e00-4aa1-b3c7-de3b0ee62360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a49f2005-f13f-4735-a471-1c9ad4f6e767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full m-auto rounded imageBanner</value>
      <webElementGuid>2e4f01c7-eca5-4cd4-8a51-01bedd7f6758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FavoritesFeed&quot;)/section[@class=&quot;desktop:grid desktop:grid-cols-12 mobile:hidden desktop:gap-4&quot;]/div[@class=&quot;flex flex-col col-span-8&quot;]/div[@class=&quot;desktop:grid desktop:grid-cols-4 desktop:gap-4&quot;]/div[@class=&quot;mr-auto&quot;]/article[@class=&quot;w-[200px] h-[300px] border-b border-gray-300 mb-4 mr-auto mobile:hidden&quot;]/a[1]/div[1]/div[@class=&quot;h-[151px] w-[200x] rounded-lg overflow-hidden relative flex&quot;]/img[@class=&quot;h-full m-auto rounded imageBanner&quot;]</value>
      <webElementGuid>6d1e1368-c9c4-4b65-a912-3140f0b65b3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FavoritesFeed']/section/div[4]/div[2]/div[2]/article/a/div/div/img</value>
      <webElementGuid>659c4b61-0067-47cc-b0a7-1082f7127324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://timnews.com.br/system/images/photos/15562810/original/open-uri20230519-18-2qfmd6?1684508195']</value>
      <webElementGuid>c52def6a-e899-4827-9983-fdc3d29a063b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/a/div/div/img</value>
      <webElementGuid>7a94b7bf-9a77-4eee-ac01-0409049263de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/images/photos/15562810/original/open-uri20230519-18-2qfmd6?1684508195' and @alt = 'https://timnews.com.br/system/images/photos/15562810/original/open-uri20230519-18-2qfmd6?1684508195']</value>
      <webElementGuid>3e8d7ba4-c859-4766-abed-85598eff6b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
