<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__h-full m-auto rounded imageBanner</name>
   <tag></tag>
   <elementGuidId>e9441e28-c55d-4665-b590-a84d8be90af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div[3]/div/div[3]/div/div[2]/article[2]/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>934f1229-78a3-4b1c-ad5f-33881c9c5847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15562844/original/open-uri20230519-19-kculj6?1684509124</value>
      <webElementGuid>457f5106-65f8-415f-ac94-34151eb4f78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>https://timnews.com.br/system/images/photos/15562844/original/open-uri20230519-19-kculj6?1684509124</value>
      <webElementGuid>d77d15c3-a274-4755-ae9b-0b9b123809d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>640px</value>
      <webElementGuid>ffeb14d0-c357-4c02-a54d-bc769291d92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>4fff703d-2c44-4ccc-93f9-386944cbeb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>deccdd0c-1f33-41d6-9278-104a59e09fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full m-auto rounded imageBanner</value>
      <webElementGuid>ad54213d-5357-48f7-9499-f83d598d3c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/main[@class=&quot;container flex-grow min-h-screen-custom mx-auto  desktop:mt-[5.9rem] mobile:mt-14&quot;]/div[@class=&quot;container relative mx-auto&quot;]/div[@class=&quot;gap-4 desktop:grid desktop:grid-cols-12&quot;]/div[@class=&quot;flex flex-col col-span-3 col-start-10&quot;]/div[@class=&quot;flex flex-col mb-2 desktop:hidden&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;mobile:px-1 flex desktop:pt-4 gap-y-6 border-t border-gray-300 mobile:flex-row desktop:flex-wrap bg-[#f2f4fa] mobile:overflow-x-scroll mobile:overflow-y-hidden mobile:hidescrollbar mobile:scroll-display-desktop mobile:scroll-display-off&quot;]/article[@class=&quot;w-[260px] h-[320px] mobile:m-2 m-auto&quot;]/a[1]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;h-[195px] w-[260px] rounded-lg overflow-hidden relative flex&quot;]/img[@class=&quot;h-full m-auto rounded imageBanner&quot;]</value>
      <webElementGuid>8188b27d-2ffe-4c5f-a497-26eb7c2f2810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div[3]/div/div[3]/div/div[2]/article[2]/a/div/div/img</value>
      <webElementGuid>028ece0e-c0a3-4818-9c5b-f492b5ba9726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='https://timnews.com.br/system/images/photos/15562844/original/open-uri20230519-19-kculj6?1684509124']</value>
      <webElementGuid>c2f3692d-9a36-4da3-af02-fb1f98a2dc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/a/div/div/img</value>
      <webElementGuid>ef329935-b2b7-44d8-ae20-3255a54faf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://timnews.com.br/system/images/photos/15562844/original/open-uri20230519-19-kculj6?1684509124' and @alt = 'https://timnews.com.br/system/images/photos/15562844/original/open-uri20230519-19-kculj6?1684509124']</value>
      <webElementGuid>3d2a899e-64c0-4455-acd1-83a80beabbf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
