<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Placar ao vivo_w-full desktoppy-1 mob_c13ef6</name>
   <tag></tag>
   <elementGuidId>d67e8df8-da10-4847-9471-3cc0ce7e3fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='search'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cce9ce28-a99c-4861-bd43-7c479d9ab871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>ec06e017-63e2-4620-8c76-123a74457c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ae479701-6322-4cf8-9f18-33fcd603985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full desktop:py-1 mobile:py-1.5 pl-10 pr-3 my-auto bg-white border rounded focus:shadow</value>
      <webElementGuid>ee313dd8-4985-4d2d-82de-af3ebc06b143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative flex flex-col h-screen-custom align-items-stretch&quot;]/section[1]/section[@class=&quot;fixed left-0 right-0 z-50 h-14&quot;]/div[@class=&quot;h-14 mobile:bg-gradient-tim&quot;]/div[@class=&quot;container relative py-[9px] mx-auto&quot;]/form[@class=&quot;flex desktop:m-auto mobile:mx-4&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;w-full desktop:py-1 mobile:py-1.5 pl-10 pr-3 my-auto bg-white border rounded focus:shadow&quot;]</value>
      <webElementGuid>b2e24d83-8f59-4d94-ae16-55ad175fae25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='search'])[2]</value>
      <webElementGuid>203e745e-b000-4a9b-adf9-65fba06fada0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/section/section/div/div/form/div/input</value>
      <webElementGuid>684665cb-2f59-4f55-9b84-986a074a4c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>82af2de7-3771-48cf-a6d3-46a6cf970816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Buscar' and @type = 'search']</value>
      <webElementGuid>4282483b-ca90-4281-be7d-a8fff4a9216b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
